import React from "react";
import { NavLink } from "react-router-dom";

const Navbar = () => {
  return (
    <>
      <div style={{ backgroundColor: "black" }}>
        <div className="center navbar_div">
        <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/"
          >
            Home
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/UseEffectApi"
          >
            Get Movies Info
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/filterWeather"
          >
            Weather
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/todo"
          >
            Todo
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/digitalClock"
          >
            DigitalClock
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/slotmachine"
          >
            Slotmachine
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/routingExample"
          >
            RoutingExample
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/pokemonApi"
          >
            PokemonApi
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/getDataFromApi"
          >
            GetDataFromApi
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/hookChallenge"
          >
            HookChallenge
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/checkAlertOnButtons"
          >
            CheckAlertOnButtons
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/parent"
          >
            Parent
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/miniNavBar"
          >
            MiniNavBar
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/notes"
          >
            Notes
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/notes/note"
          >
            Test
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/counterRH"
          >
            CounterRH
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/forms"
          >
            Forms
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/hooks"
          >
            Hooks
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/findFav2"
          >
            FindFav2
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/findFav"
          >
            FindFav
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/params/Gagan/Hayer"
          >
            Params
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/GetUserHistory"
          >
            GetUserHistory
          </NavLink>
          <NavLink
            exact
            className="nav_Link"
            activeClassName="active_class"
            to="/searchFilter"
          >
            SearchFilter
          </NavLink>
        </div>
      </div>
    </>
  );
};

export default Navbar;
